In [1]:
#importing libraries
import pandas as pd
import numpy as np

In [2]:
#reading the csv file 
df = pd.read_csv('online_shoppers_intention_DATAPTDIC19.csv', sep=';')

In [3]:
df.head(10)

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0.0,0,0.0,0,1.0,0,0.200000,0.200000,0,0.0,Feb,1.0,1,1,1,Returning_Visitor,False,FALSE
1,0.0,0,0.0,0,2.0,64,0.000000,0.100000,0,0.0,Feb,2.0,2,1,2,Returning_Visitor,False,FALSE
2,0.0,-1,0.0,-1,1.0,-1,0.200000,0.200000,0,0.0,Feb,4.0,1,9,3,Returning_Visitor,False,FALSE
3,0.0,0,0.0,0,2.0,2.666.666.667,0.050000,0.140000,0,0.0,Feb,3.0,2,2,4,Returning_Visitor,False,FALSE
4,0.0,0,0.0,0,10.0,627.5,0.020000,0.050000,0,0.0,Feb,3.0,3,1,4,Returning_Visitor,True,FALSE
5,0.0,0,0.0,0,19.0,1.542.166.667,0.015789,0.024561,0,0.0,Feb,2.0,2,1,3,Returning_Visitor,False,FALSE
6,0.0,-1,0.0,-1,1.0,-1,0.200000,0.200000,0,0.4,Feb,2.0,4,3,3,Returning_Visitor,False,FALSE
7,0.0,0,0.0,0,2.0,37,0.000000,0.100000,0,0.8,Feb,2.0,2,2,3,Returning_Visitor,False,FALSE
8,0.0,0,0.0,0,3.0,738,0.000000,0.022222,0,0.4,Feb,2.0,4,1,2,Returning_Visitor,False,FALSE
9,0.0,0,0.0,0,3.0,395,0.000000,0.066667,0,0.0,Feb,1.0,1,3,3,Returning_Visitor,False,FALSE

In [5]:
df[df.Administrative_Duration == '-1']

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
2,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Feb,4.0,1,9,3,Returning_Visitor,False,FALSE
6,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.4,Feb,2.0,4,3,3,Returning_Visitor,False,FALSE
14,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Feb,1.0,1,4,3,RETURNING,False,FALSE
19,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Feb,3.0,3,1,3,Returning_Visitor,False,FALSE
22,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Feb,2.0,2,4,1,Returning_Visitor,True,FALSE
43,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.6,Feb,2.0,2,3,2,Returning_Visitor,False,FALSE
44,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Feb,1.0,1,3,4,Returning_Visitor,True,FALSE
55,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Feb,2.0,2,4,3,Returning_Visitor,False,FALSE
111,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Feb,3.0,2,3,3,Returning_Visitor,False,FALSE
117,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Feb,2.0,2,7,3,Returning_Visitor,False,FALSE
151,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.6,Feb,4.0,2,1,3,Returning_Visitor,False,FALSE
152,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Feb,2.0,4,1,1,Returning_Visitor,False,FALSE
183,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Mar,1.0,1,1,1,Returning_Visitor,False,FALSE
255,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Mar,2.0,2,2,3,Returning_Visitor,False,FALSE
332,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Mar,3.0,2,7,1,Returning_Visitor,False,FALSE
339,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Mar,3.0,2,3,1,Returning_Visitor,False,FALSE
350,0.0,-1,0.0,-1,1.0,-1,0.0,0.066667,0,0.0,Mar,2.0,2,7,1,Returning_Visitor,False,FALSE
370,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Mar,1.0,1,3,3,Returning_Visitor,False,FALSE
389,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Mar,3.0,2,3,3,Returning_Visitor,False,FALSE
1088,0.0,-1,0.0,-1,1.0,-1,0.0,0.100000,0,0.0,Mar,2.0,2,2,6,Returning_Visitor,False,FALSE
1093,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Mar,2.0,5,2,3,Returning_Visitor,False,FALSE
1100,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Mar,2.0,5,1,3,Returning_Visitor,False,FALSE
2528,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,May,3.0,2,5,6,Returning_Visitor,False,FALSE
2591,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,May,2.0,2,9,3,Returning_Visitor,False,FALSE
2684,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,May,1.0,1,1,20,Returning_Visitor,False,FALSE
2685,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,May,2.0,4,4,3,Returning_Visitor,False,FALSE
2692,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,May,2.0,10,5,1,Returning_Visitor,False,FALSE
3149,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Nov,2.0,2,1,13,Returning_Visitor,False,FALSE
3427,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Jul,1.0,1,3,1,Returning_Visitor,False,FALSE
3675,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Nov,1.0,1,9,2,Returning_Visitor,False,FALSE
3964,0.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Nov,1.0,8,2,1,Returning_Visitor,False,FALSE
5754,1.0,-1,0.0,-1,1.0,-1,0.2,0.200000,0,0.0,Feb,1.0,2,1,5,Returning_Visitor,True,FALSE
6268,1.0,-1,0.0,-1,1.0,-1,0.0,0.066667,0,0.0,May,3.0,2,1,4,Returning_Visitor,False,FALSE

In [ ]:
df.info()

'''There little to almost non null values as it seems, and the dtypes since to be fine, althought there are 
several column that seem to be wrongly names as object:
- Administrative_Duration
- Informational_Duration
- ProductRelated_Duration
- PageValues
- Month 
- Visitor Type
- Revenue'''

In [ ]:
print(df.isnull().sum())

'''As we said previously, there are little to almost null values. So far, we don't have info to know why we have 
these null values.'''

##### Let's dig deeper into each of the variables to understand better the values and the possible null values in the columns of :

- Administrative             15
- Administrative_Duration    14
- Informational              14
- Informational_Duration     14
- ProductRelated             15
- ProductRelated_Duration    14
- BounceRates                14
- ExitRates                  14
- SpecialDay                  1
- Month                       5
- OperatingSystems            1
- VisitorType                 3

In [ ]:
df.Administrative_Duration.unique() #there are some nan values

In [ ]:
df.Administrative.unique() #there are some nan values

##### We need to change the data types of the columns previously named to their proper type, which is numeric. 

###### We will use the apply function and pd.to_numeric for it.

In [ ]:
wrong_dtypes = ['Administrative_Duration',
                        'Informational_Duration',
                        'ProductRelated_Duration',
                        'PageValues']

In [ ]:
df[wrong_dtypes] = df[wrong_dtypes].apply(pd.to_numeric, errors='coerce')

In [ ]:
print(df.dtypes)

'''All the columns are the correct data type besides month, let's change that one too'''

In [ ]:
df.Month.replace('FEBR','Feb', inplace=True)

'''We don't have information for all the months, we are missing January & April, plus we also have some nan values'''
df.Month.isnull().sum()

In [ ]:
df.dtypes

##### Dealing with null values :

In [ ]:
df.isnull().sum()

After changing the data types to the correspondent ones, we discover that there are four variables with
a lot of null values. Administrative Duration, Informational_Duration, ProductRelated_Duration and Page Values. 

Let's take a look into them to understand a little bit better what we have.

In [ ]:
df[df['ProductRelated_Duration'].isnull()]

In [ ]:
df.iloc[df[(df.isnull().sum(axis=1) >= 8)].index]

In [ ]:
df.Revenue.value_counts()

In [ ]:
df.Administrative_Duration.sort_values(ascending=False)